In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
dt = pd.read_csv('supplements_sales_data.csv', sep=';')
dt.head()

,Date,Product Name,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform
0,2020/01/06,Whey Protein,Protein,143,31.98,4573.14,0.03,2,Canada,Walmart
1,2020/01/06,Vitamin C,Vitamin,139,42.51,5908.89,0.04,0,UK,Amazon
2,2020/01/06,Fish Oil,Omega,161,12.91,2078.51,0.25,0,Canada,Amazon
3,2020/01/06,Multivitamin,Vitamin,140,16.07,2249.80,0.08,0,Canada,Walmart
4,2020/01/06,Pre-Workout,Performance,157,35.47,5568.79,0.25,3,Canada,iHerb

In [4]:
dt.describe()

        Units Sold        Price       Revenue     Discount  Units Returned
count  4384.000000  4384.000000   4384.000000  4384.000000     4384.000000
mean    150.200274    34.781229   5226.569446     0.124398        1.531478
std      12.396099    14.198309   2192.491946     0.071792        1.258479
min     103.000000    10.000000   1284.000000     0.000000        0.000000
25%     142.000000    22.597500   3349.372500     0.060000        1.000000
50%     150.000000    34.720000   5173.140000     0.120000        1.000000
75%     158.000000    46.712500   7009.960000     0.190000        2.000000
max     194.000000    59.970000  10761.850000     0.250000        8.000000

In [8]:
print(dt.dtypes)

Date               object
Product Name       object
Category           object
Units Sold          int64
Price             float64
Revenue           float64
Discount          float64
Units Returned      int64
Location           object
Platform           object
dtype: object

In [11]:
dt['Date'] = pd.to_datetime(dt['Date'])

In [18]:
#strip whitespace fic capitalisation
for col in ['Product Name', 'Category', 'Location', 'Platform']:
    dt[col] = dt[col].str.strip().str.title()


#checking missing values 
dt_missing = dt.isnull().sum()
print(dt_missing)

#duplicates 
dubes = dt.duplicated().sum()
print(dubes)

Date              0
Product Name      0
Category          0
Units Sold        0
Price             0
Revenue           0
Discount          0
Units Returned    0
Location          0
Platform          0
dtype: int64
0

In [24]:
#get a propotion of products that came back 
dt['Return rates'] = dt['Units Returned'] / dt['Units Sold']

#calculates what the customer actually paid after discount
dt['Effective Price'] = dt['Price'] * (1 - dt['Discount'])

#divides total revenue by units sold to the average earning per item sold
dt['Revenue Per Unit'] = dt['Revenue'] / dt['Units Sold']
print(dt.head(10))

        Date       Product Name     Category  Units Sold  Price  Revenue  \
0 2020-01-06       Whey Protein      Protein         143  31.98  4573.14
1 2020-01-06          Vitamin C      Vitamin         139  42.51  5908.89
2 2020-01-06           Fish Oil        Omega         161  12.91  2078.51
3 2020-01-06       Multivitamin      Vitamin         140  16.07  2249.80
4 2020-01-06        Pre-Workout  Performance         157  35.47  5568.79
5 2020-01-06               Bcaa   Amino Acid         154  41.19  6343.26
6 2020-01-06           Creatine  Performance         134  32.49  4353.66
7 2020-01-06               Zinc      Mineral         147  46.68  6861.96
8 2020-01-06  Collagen Peptides      Protein         147  10.96  1611.12
9 2020-01-06          Magnesium      Mineral         134  20.76  2781.84

   Discount  Units Returned Location Platform  Return rates  Effective Price  \
0      0.03               2   Canada  Walmart      0.013986          31.0206
1      0.04               0       Uk   Amazon      0.000000          40.8096
2      0.25               0   Canada   Amazon      0.000000           9.6825
3      0.08               0   Canada  Walmart      0.000000          14.7844
4      0.25               3   Canada    Iherb      0.019108          26.6025
5      0.13               1       Uk  Walmart      0.006494          35.8353
6      0.05               1       Uk  Walmart      0.007463          30.8655
7      0.19               0   Canada   Amazon      0.000000          37.8108
8      0.06               2      Usa   Amazon      0.013605          10.3024
9      0.00               0   Canada   Amazon      0.000000          20.7600

   Revenue Per Unit
0             31.98
1             42.51
2             12.91
3             16.07
4             35.47
5             41.19
6             32.49
7             46.68
8             10.96
9             20.76