In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('supplements_sales_data.csv', sep=';')
df.head()

,Date,Product Name,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform
0,2020/01/06,Whey Protein,Protein,143,31.98,4573.14,0.03,2,Canada,Walmart
1,2020/01/06,Vitamin C,Vitamin,139,42.51,5908.89,0.04,0,UK,Amazon
2,2020/01/06,Fish Oil,Omega,161,12.91,2078.51,0.25,0,Canada,Amazon
3,2020/01/06,Multivitamin,Vitamin,140,16.07,2249.80,0.08,0,Canada,Walmart
4,2020/01/06,Pre-Workout,Performance,157,35.47,5568.79,0.25,3,Canada,iHerb

In [5]:
df.tail()

,Date,Product Name,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform
4379,2025/03/31,Melatonin,Sleep Aid,160,47.79,7646.40,0.21,1,USA,iHerb
4380,2025/03/31,Biotin,Vitamin,154,38.12,5870.48,0.22,1,UK,Walmart
4381,2025/03/31,Green Tea Extract,Fat Burner,139,20.40,2835.60,0.12,3,USA,iHerb
4382,2025/03/31,Iron Supplement,Mineral,154,18.31,2819.74,0.23,2,Canada,Amazon
4383,2025/03/31,Electrolyte Powder,Hydration,178,39.12,6963.36,0.23,0,UK,iHerb

In [7]:
#how many rows and columns are there 
df.shape

(4384, 10)

In [8]:
df.columns

Index(['Date', 'Product Name', 'Category', 'Units Sold', 'Price', 'Revenue',
       'Discount', 'Units Returned', 'Location', 'Platform'],
      dtype='object')

In [9]:
df.dtypes

Date               object
Product Name       object
Category           object
Units Sold          int64
Price             float64
Revenue           float64
Discount          float64
Units Returned      int64
Location           object
Platform           object
dtype: object

In [13]:
df.info

<bound method DataFrame.info of             Date        Product Name     Category  Units Sold  Price  Revenue  \
0     2020/01/06        Whey Protein      Protein         143  31.98  4573.14
1     2020/01/06           Vitamin C      Vitamin         139  42.51  5908.89
2     2020/01/06            Fish Oil        Omega         161  12.91  2078.51
3     2020/01/06        Multivitamin      Vitamin         140  16.07  2249.80
4     2020/01/06         Pre-Workout  Performance         157  35.47  5568.79
...          ...                 ...          ...         ...    ...      ...
4379  2025/03/31           Melatonin    Sleep Aid         160  47.79  7646.40
4380  2025/03/31              Biotin      Vitamin         154  38.12  5870.48
4381  2025/03/31   Green Tea Extract   Fat Burner         139  20.40  2835.60
4382  2025/03/31     Iron Supplement      Mineral         154  18.31  2819.74
4383  2025/03/31  Electrolyte Powder    Hydration         178  39.12  6963.36

      Discount  Units Returned Location Platform
0         0.03               2   Canada  Walmart
1         0.04               0       UK   Amazon
2         0.25               0   Canada   Amazon
3         0.08               0   Canada  Walmart
4         0.25               3   Canada    iHerb
...        ...             ...      ...      ...
4379      0.21               1      USA    iHerb
4380      0.22               1       UK  Walmart
4381      0.12               3      USA    iHerb
4382      0.23               2   Canada   Amazon
4383      0.23               0       UK    iHerb

[4384 rows x 10 columns]>

In [10]:
#statistical summary of the data 
df.describe()

        Units Sold        Price       Revenue     Discount  Units Returned
count  4384.000000  4384.000000   4384.000000  4384.000000     4384.000000
mean    150.200274    34.781229   5226.569446     0.124398        1.531478
std      12.396099    14.198309   2192.491946     0.071792        1.258479
min     103.000000    10.000000   1284.000000     0.000000        0.000000
25%     142.000000    22.597500   3349.372500     0.060000        1.000000
50%     150.000000    34.720000   5173.140000     0.120000        1.000000
75%     158.000000    46.712500   7009.960000     0.190000        2.000000
max     194.000000    59.970000  10761.850000     0.250000        8.000000

In [14]:
#do we have missing values 
df.isna().sum()

Date              0
Product Name      0
Category          0
Units Sold        0
Price             0
Revenue           0
Discount          0
Units Returned    0
Location          0
Platform          0
dtype: int64