In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('supplements_sales_data.csv', sep=';')
df.head()

,Date,Product Name,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform
0,2020/01/06,Whey Protein,Protein,143,31.98,4573.14,0.03,2,Canada,Walmart
1,2020/01/06,Vitamin C,Vitamin,139,42.51,5908.89,0.04,0,UK,Amazon
2,2020/01/06,Fish Oil,Omega,161,12.91,2078.51,0.25,0,Canada,Amazon
3,2020/01/06,Multivitamin,Vitamin,140,16.07,2249.80,0.08,0,Canada,Walmart
4,2020/01/06,Pre-Workout,Performance,157,35.47,5568.79,0.25,3,Canada,iHerb

In [5]:
df.tail()

,Date,Product Name,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform
4379,2025/03/31,Melatonin,Sleep Aid,160,47.79,7646.40,0.21,1,USA,iHerb
4380,2025/03/31,Biotin,Vitamin,154,38.12,5870.48,0.22,1,UK,Walmart
4381,2025/03/31,Green Tea Extract,Fat Burner,139,20.40,2835.60,0.12,3,USA,iHerb
4382,2025/03/31,Iron Supplement,Mineral,154,18.31,2819.74,0.23,2,Canada,Amazon
4383,2025/03/31,Electrolyte Powder,Hydration,178,39.12,6963.36,0.23,0,UK,iHerb

In [7]:
#how many rows and columns are there 
df.shape

(4384, 10)

In [8]:
df.columns

Index(['Date', 'Product Name', 'Category', 'Units Sold', 'Price', 'Revenue',
       'Discount', 'Units Returned', 'Location', 'Platform'],
      dtype='object')

In [9]:
df.dtypes

Date               object
Product Name       object
Category           object
Units Sold          int64
Price             float64
Revenue           float64
Discount          float64
Units Returned      int64
Location           object
Platform           object
dtype: object

In [13]:
df.info

<bound method DataFrame.info of             Date        Product Name     Category  Units Sold  Price  Revenue  \
0     2020/01/06        Whey Protein      Protein         143  31.98  4573.14
1     2020/01/06           Vitamin C      Vitamin         139  42.51  5908.89
2     2020/01/06            Fish Oil        Omega         161  12.91  2078.51
3     2020/01/06        Multivitamin      Vitamin         140  16.07  2249.80
4     2020/01/06         Pre-Workout  Performance         157  35.47  5568.79
...          ...                 ...          ...         ...    ...      ...
4379  2025/03/31           Melatonin    Sleep Aid         160  47.79  7646.40
4380  2025/03/31              Biotin      Vitamin         154  38.12  5870.48
4381  2025/03/31   Green Tea Extract   Fat Burner         139  20.40  2835.60
4382  2025/03/31     Iron Supplement      Mineral         154  18.31  2819.74
4383  2025/03/31  Electrolyte Powder    Hydration         178  39.12  6963.36

      Discount  Units Returned Location Platform
0         0.03               2   Canada  Walmart
1         0.04               0       UK   Amazon
2         0.25               0   Canada   Amazon
3         0.08               0   Canada  Walmart
4         0.25               3   Canada    iHerb
...        ...             ...      ...      ...
4379      0.21               1      USA    iHerb
4380      0.22               1       UK  Walmart
4381      0.12               3      USA    iHerb
4382      0.23               2   Canada   Amazon
4383      0.23               0       UK    iHerb

[4384 rows x 10 columns]>

In [10]:
#statistical summary of the data 
df.describe()

        Units Sold        Price       Revenue     Discount  Units Returned
count  4384.000000  4384.000000   4384.000000  4384.000000     4384.000000
mean    150.200274    34.781229   5226.569446     0.124398        1.531478
std      12.396099    14.198309   2192.491946     0.071792        1.258479
min     103.000000    10.000000   1284.000000     0.000000        0.000000
25%     142.000000    22.597500   3349.372500     0.060000        1.000000
50%     150.000000    34.720000   5173.140000     0.120000        1.000000
75%     158.000000    46.712500   7009.960000     0.190000        2.000000
max     194.000000    59.970000  10761.850000     0.250000        8.000000

In [14]:
#do we have missing values 
df.isna().sum()

Date              0
Product Name      0
Category          0
Units Sold        0
Price             0
Revenue           0
Discount          0
Units Returned    0
Location          0
Platform          0
dtype: int64

In [15]:
#duplicates 
df.duplicated().sum()

np.int64(0)

In [19]:
df['Date'] = pd.to_datetime(df['Date'])
df['Date']

0      2020-01-06
1      2020-01-06
2      2020-01-06
3      2020-01-06
4      2020-01-06
          ...
4379   2025-03-31
4380   2025-03-31
4381   2025-03-31
4382   2025-03-31
4383   2025-03-31
Name: Date, Length: 4384, dtype: datetime64[ns]

In [28]:
#standardise text
#check how many unique values are there
df['Platform'].value_counts()

Platform
iHerb      1499
Amazon     1473
Walmart    1412
Name: count, dtype: int64

In [31]:
(df['Platform'] != df['Platform'].str.strip()).sum()

np.int64(0)

In [29]:
df['Category'].unique()

array(['Protein', 'Vitamin', 'Omega', 'Performance', 'Amino Acid',
       'Mineral', 'Herbal', 'Sleep Aid', 'Fat Burner', 'Hydration'],
      dtype=object)

In [35]:
df['Location'].unique()

0       True
1       True
2       True
3       True
4       True
        ...
4379    True
4380    True
4381    True
4382    True
4383    True
Name: Location, Length: 4384, dtype: bool

In [38]:
(df['Location'] != df['Location'].str.strip()).sum()

np.int64(0)

In [24]:
df['Product Name'].nunique()

16

In [37]:
#check whitespace 
(df['Platform'] != df['Platform'].str.strip()).sum()

np.int64(0)

In [40]:
#Filtering data 
usa_data = df[df['Location'] == 'USA']
usa_data

,Date,Product Name,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform
8,2020-01-06,Collagen Peptides,Protein,147,10.96,1611.12,0.06,2,USA,Amazon
10,2020-01-06,Ashwagandha,Herbal,181,15.49,2803.69,0.14,1,USA,Amazon
11,2020-01-06,Melatonin,Sleep Aid,164,34.41,5643.24,0.04,1,USA,Walmart
15,2020-01-06,Electrolyte Powder,Hydration,154,35.92,5531.68,0.04,2,USA,Amazon
17,2020-01-13,Vitamin C,Vitamin,128,10.61,1358.08,0.24,2,USA,Amazon
...,...,...,...,...,...,...,...,...,...,...
4366,2025-03-24,Iron Supplement,Mineral,167,53.89,8999.63,0.20,0,USA,Amazon
4370,2025-03-31,Fish Oil,Omega,139,44.67,6209.13,0.21,4,USA,iHerb
4376,2025-03-31,Collagen Peptides,Protein,146,52.79,7707.34,0.13,1,USA,Amazon
4379,2025-03-31,Melatonin,Sleep Aid,160,47.79,7646.40,0.21,1,USA,iHerb
4381,2025-03-31,Green Tea Extract,Fat Burner,139,20.40,2835.60,0.12,3,USA,iHerb

In [41]:
#multiple conditions 
#the sales in USA via amazon 
df[
    (df['Location'] == 'USA') &
    (df['Platform'] == 'Amazon')
]

,Date,Product Name,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform
8,2020-01-06,Collagen Peptides,Protein,147,10.96,1611.12,0.06,2,USA,Amazon
10,2020-01-06,Ashwagandha,Herbal,181,15.49,2803.69,0.14,1,USA,Amazon
15,2020-01-06,Electrolyte Powder,Hydration,154,35.92,5531.68,0.04,2,USA,Amazon
17,2020-01-13,Vitamin C,Vitamin,128,10.61,1358.08,0.24,2,USA,Amazon
19,2020-01-13,Multivitamin,Vitamin,137,14.92,2044.04,0.17,2,USA,Amazon
...,...,...,...,...,...,...,...,...,...,...
4346,2025-03-17,Ashwagandha,Herbal,162,14.09,2282.58,0.03,3,USA,Amazon
4351,2025-03-17,Electrolyte Powder,Hydration,160,29.17,4667.20,0.07,3,USA,Amazon
4365,2025-03-24,Green Tea Extract,Fat Burner,150,13.36,2004.00,0.01,2,USA,Amazon
4366,2025-03-24,Iron Supplement,Mineral,167,53.89,8999.63,0.20,0,USA,Amazon
4376,2025-03-31,Collagen Peptides,Protein,146,52.79,7707.34,0.13,1,USA,Amazon

In [43]:
locations = ['USA', 'Canada', 'UK']
df[df['Location'].isin(locations)]

,Date,Product Name,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform
0,2020-01-06,Whey Protein,Protein,143,31.98,4573.14,0.03,2,Canada,Walmart
1,2020-01-06,Vitamin C,Vitamin,139,42.51,5908.89,0.04,0,UK,Amazon
2,2020-01-06,Fish Oil,Omega,161,12.91,2078.51,0.25,0,Canada,Amazon
3,2020-01-06,Multivitamin,Vitamin,140,16.07,2249.80,0.08,0,Canada,Walmart
4,2020-01-06,Pre-Workout,Performance,157,35.47,5568.79,0.25,3,Canada,iHerb
...,...,...,...,...,...,...,...,...,...,...
4379,2025-03-31,Melatonin,Sleep Aid,160,47.79,7646.40,0.21,1,USA,iHerb
4380,2025-03-31,Biotin,Vitamin,154,38.12,5870.48,0.22,1,UK,Walmart
4381,2025-03-31,Green Tea Extract,Fat Burner,139,20.40,2835.60,0.12,3,USA,iHerb
4382,2025-03-31,Iron Supplement,Mineral,154,18.31,2819.74,0.23,2,Canada,Amazon
4383,2025-03-31,Electrolyte Powder,Hydration,178,39.12,6963.36,0.23,0,UK,iHerb

In [44]:
products = ['Vitamin C', 'Biotin', 'Whey Protein']
df[df['Product Name'].isin(products)]

,Date,Product Name,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform
0,2020-01-06,Whey Protein,Protein,143,31.98,4573.14,0.03,2,Canada,Walmart
1,2020-01-06,Vitamin C,Vitamin,139,42.51,5908.89,0.04,0,UK,Amazon
12,2020-01-06,Biotin,Vitamin,159,28.79,4577.61,0.10,1,UK,iHerb
16,2020-01-13,Whey Protein,Protein,150,12.08,1812.00,0.02,2,UK,Amazon
17,2020-01-13,Vitamin C,Vitamin,128,10.61,1358.08,0.24,2,USA,Amazon
...,...,...,...,...,...,...,...,...,...,...
4353,2025-03-24,Vitamin C,Vitamin,136,58.55,7962.80,0.09,4,Canada,Walmart
4364,2025-03-24,Biotin,Vitamin,150,21.06,3159.00,0.06,1,UK,Amazon
4368,2025-03-31,Whey Protein,Protein,148,15.17,2245.16,0.07,1,UK,Amazon
4369,2025-03-31,Vitamin C,Vitamin,157,57.08,8961.56,0.20,2,UK,iHerb
4380,2025-03-31,Biotin,Vitamin,154,38.12,5870.48,0.22,1,UK,Walmart

In [55]:
#Sorting
#top selling product 
df.sort_values(['Revenue'], ascending=False)

,Date,Product Name,Category,Units Sold,Price,Revenue,Discount,Units Returned,Location,Platform
2384,2022-11-14,Whey Protein,Protein,187,57.55,10761.85,0.13,2,USA,Amazon
2835,2023-05-29,Multivitamin,Vitamin,179,59.70,10686.30,0.17,0,UK,iHerb
389,2020-06-22,BCAA,Amino Acid,174,59.18,10297.32,0.06,5,UK,iHerb
4034,2024-11-04,Fish Oil,Omega,186,55.13,10254.18,0.11,0,Canada,Amazon
1277,2021-07-12,Green Tea Extract,Fat Burner,174,58.90,10248.60,0.25,2,Canada,Walmart
...,...,...,...,...,...,...,...,...,...,...
3764,2024-07-08,Pre-Workout,Performance,136,10.14,1379.04,0.08,0,UK,Walmart
17,2020-01-13,Vitamin C,Vitamin,128,10.61,1358.08,0.24,2,USA,Amazon
899,2021-02-01,Multivitamin,Vitamin,129,10.50,1354.50,0.02,2,UK,iHerb
3371,2024-01-15,Melatonin,Sleep Aid,133,10.17,1352.61,0.10,0,USA,iHerb
801,2020-12-21,Vitamin C,Vitamin,120,10.70,1284.00,0.14,3,Canada,Walmart

In [59]:
#Aggregation 
#df['Revenue'].mean()

#df['Revenue'].median()

df['Revenue'].sum()

#df['Revenue'].max()

#df['Revenue'].min()

#df['Revenue'].describe()

np.float64(22913280.45)